### ISSUE TITLE
Write contributing instructions

### ISSUE THREAD

**Issue by ADubhlaoich** [ADubhlaoich/swing-ie#1]
There's nobody else working on the website besides me - but that might not be the case for the future.

A contributing file would best serve these possible people in the future, and can be linked from the README. It could serve as a notice of the stack & methods used on the website, as well as a simple list of instructions on how to contribute.

**Comment by afs2015** [comment]
A lot of people include it in the README file unless if a project grows to a certain size then they usually have a seperate area for contributing, installation, and project documentation.

**Comment by ADubhlaoich** [comment]
@afs2015 Fair point - There's actually no need to go have a separate file. I've never heard it applied to documentation, but premature optimization is bad and all that jazz. I'll update the README accordingly later today.
